############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Blog"
url = "/blog"
weight = 3

# [[main]]
# name = "Thoughts"
# url = "/thoughts"
# weight = 4

# [[main]]
# name = "Social"
# url = "/social"
# weight = 5

[[main]]
name = "Collectables"
url = "/collectables"
weight = 6

[[main]]
name = "Contact"
url = "/contact"
weight = 7


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Blog"
url = "/blog"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
